export type ListsModel = {
  title?: string | null;
  _id?: string | null;
  description?: string | null;
  body?: string | null;
  featuredImagePath?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  topicId?: string | null;
  status?: string | null;
  subTitle?: string | null;
  slug?: string | null;
  catId?: string | null;
  image?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  importId?: string | null;
  rankingScore?: string | null;
  ratingScore?: string | null;
  views?: string | null;
  selectedImage?: any;
};
